### ISSUE TITLE
Broken Runes Spawn

### ISSUE THREAD

**Issue by xtasy99** [BOTRaiquia/dota2buttemplate_fixed#20]
https://github.com/Snoresville/dota2buttemplate_fixed/blob/a12e84a82b8b92e57e369b4d93c95257c454d37b/game/dota_addons/addon_template_butt/scripts/vscripts/settings_misc.lua#L45

This logic is now False by default, rune spawns is now another broken custom game feature. The logic needs to be set to true after an 'else' in this. It's an easy fix.
At least now SetRuneEnabled works with all runes.

**Comment by Snoresville** [comment]
I'm confused because I don't know what you mean; is it this line specifically that needs to be set to true, or is it the 
`if false then`
part, where I need to replace the `false` with `true`?

I believe you can make a pull request and make the fix, let people check what you mean by this.

**Comment by xtasy99** [comment]
'SetUseDefaultDOTARuneSpawnLogic' is False by default, it used to be True by default. This has no use now.

The runes spawn is broken for any custom game, every rune spot spawn random runes. Adding the True to the rune logic fix it.

I dont know how to pull request

**Comment by Snoresville** [comment]
Looks like a good exercise for you. Either make a new branch on this repo or fork it, make your changes, and make a pull request.

**Comment by Snoresville** [comment]
Sorry, this isn't the correct way of performing a pull request. In the world of GitHub, we can make changes on branches or forks of a main repository, each branch/fork allowing the development of a specific purpose without influencing main. 

After completing development, you do a pull request so that your changes can be integrated into the main repository. Usually there will be other people proof-reading your changes, which is the beauty of this process as it allows greater confidence and if things go wrong with the changes, it can be discussed.

I'll reopen this for now until the pull request is done.
